### ISSUE TITLE
Parameter "index_type" should resemble Elasticsearch lingo (more closely)

### ISSUE THREAD

**Issue by konradkonrad** [logstash-plugins/logstash-output-elasticsearch#102]
Consider me a user. **)*
I had a hard (and embarrassing) time figuring out the parameter for setting the `doc_type` (used in python) or `_type` (native) for the Elasticsearch output. Here I'll take the embarrassment one level further and blame it on you ;)

It may seem obvious once learned, but: coming from Elasticsearch, I *never ever* encountered the term `index_type`. Please consider changing or aliasing the parameter name, or at least mention it in the docs for `index_type` with one of the more typical synonyms. Maybe use `document_type`, since you already use `document_id`.

Furthermore I wonder, if the docs are correct?
```
index_type
*    Value type is string
*    There is no default value for this setting. 
```
it may have happened somewhere else in the processing chain, but without setting the parameter, my events ended up with the mapping-type `logs`.

*) well, maybe a little absent-minded, but that's how some of us are...

**Comment by simmel** [comment]
+1

**Comment by jordansissel** [comment]
I agree with the complaint:
* The `index_type` default is incorrectly described in the docs
* I think the name is poor, it's really document type (as will be addressed in #105).

<3 for the details :)

**Comment by celesteking** [comment]
What is index_type / document_type and why do I need it?

**Comment by GrahamHannington** [comment]
document_type is better than index_type.

Elasticsearch should clarify its own documentation, and abandon its definitions of "type" (as a single, unqualified word) and "mapping type" in favor of "document type".

From the Elasticsearch documentation topic "[Mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html)":

> In Elasticsearch, an index may store documents of different "mapping types". Elasticsearch allows one to associate multiple mapping definitions for each mapping type.

From the [Elasticsearch glossary](https://www.elastic.co/guide/en/elasticsearch/reference/current/glossary.html#glossary-type):

> **type**
> A type is like a table in a relational database. Each type has a list of fields that can be specified for documents of that type. The mapping defines how each field in the document is analyzed. 

From the Elasticsearch documentation topic "[Core Types]()":

> The text based string type is the most basic type

Assigning a product-specific meaning to the unqualified term "type" is problematic in itself, but these problems are compounded when the same product assigns meanings to the qualified term that are _related_ to the unqualified meaning, but are not _qualifications_ of the original meaning; they refer to something else.

Product terminology should follow established grammatical conventions: a red rose is a rose that is red in color; not, say, a rose petal. Elasticsearch's use of "type" breaks this convention, with predictably confusing results.

I prefer the term "document type" to "mapping type" because:

* Unless I have missed something (it's quite possible): "mapping" in this sense applies specifically to documents - so, no need for an indirect qualification like "mapping".
* Admittedly, this reason is subjective: the term "document type" applies to a document in an intuitively similar way that the term "string type" applies to the string "Hello", just at a higher hierarchical level.

I don't have a problem with Elasticsearch's use of the term "mapping" to describe what a document type is (or does).
