### ISSUE TITLE
How to put logstash-output-elasticsearch on an ELK stack

### ISSUE THREAD

**Issue by sasha198407** [logstash-plugins/logstash-output-elasticsearch#1036]
Hello. I'm starting to learn docker. I put the ELK stack in the docker. And now how to put logstash-output-email there. Thanks to all.

**Comment by kares** [comment]
The documentation should cover the case of where to put your configuration when using Logstash in Docker:
https://www.elastic.co/guide/en/logstash/current/docker-config.html#_pipeline_configuration

Closing the issue, esp. since it's not related to the plugin - please use the forums for general questions.
