### ISSUE TITLE
Default values of `http_compression` and `compression_level` are incosistent

### ISSUE THREAD

**Issue by andsel** [logstash-plugins/logstash-output-elasticsearch#1170]
#### Tell us about the issue

**Description:**  

With version `11.17.0` the setting `http_compression` (default value `false`) was deprecated and replaced by `compression_level` (default value `1`, which is the minimal compression level).
Given that `compression_level` by default is 1, which means "compression enabled" is opposite to the (now deprecated) default value of `http_compression` .

Update the default value to `http_compression` tu `true`.

Maybe it's not just documentation change.

**URL:** 

[Example: https://www.elastic.co/guide/en/logstash/current/introduction.html](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-compression_level)

**Anything else?**

**Comment by yaauie** [comment]
Yes, http compression is on by default, but the `http_compression` config option itself effectively no longer _has_ a default value because it is now simply a deprecated alias that is only consulted when (a) it is explicitly given and (b) the preferred `compression_level` config option is not explicitly given.

**Comment by andsel** [comment]
I would close this with "works as expected no changes requested" motivation
