### ISSUE TITLE
Add support for publish_host

### ISSUE THREAD

**Issue by leedm777** [logstash-plugins/logstash-output-elasticsearch#278]
When there is a NAT between ES and Logstash (such as when Logstash is running within a Docker container), it would be nice to be able to specify the `publish_host` when using the `node` protocol, so that the Logstash client can be reachable from the ES instances.

The options within ES is documented [on their Network Settings page](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html).

As a workaround, I'm running the container with `--net=host`, which gives the container access to the host network interfaces.

**Comment by untergeek** [comment]
As of the current version, this plugin is http only.  Please move your request to https://github.com/logstash-plugins/logstash-output-elasticsearch_java

Please note that we are doing this as the http client is recommended and preferred to using a node client within Logstash, in part because it's much easier to secure HTTP traffic.

**Comment by leedm777** [comment]
Oh, didn't realize there were two different plugins. I see it's already there in logstash-plugins/logstash-output-elasticsearch_java#8.

Sorry about the noise. Thanks!
