### ISSUE TITLE
embedded not supported anymore

### ISSUE THREAD

**Issue by nlopes** [logstash-plugins/logstash-output-elasticsearch#293]
embedded and embedded_http_port were removed without ever going through the obsolete process afaik.

Is there a reason why these were dropped, even though I don't find that in any changelog?
I am wondering if there is some underlying incompatibility that I don't know of. If there is, documentation should reflect that those were dropped.

If this was done in accident, can that be re-included? It's very useful for testing locally.
The commit that dropped this is https://github.com/logstash-plugins/logstash-output-elasticsearch/commit/6e95c72946c8002400bc17a212cec2df74a1de77

Also, in the Breaking changes documentation, they appear as "new flags", not as "dropped/removed flags": https://www.elastic.co/guide/en/logstash/2.0/breaking-changes.html
```
New options: bind_host, bind_port, cluster, embedded, embedded_http_port, port, sniffing_delay
```

**Comment by untergeek** [comment]
It is intentional.  We are trying to shrink the default size of Logstash, which is quite large with all of the plugins.  This means not bundling the java version (and the accompanying jar files) and using only the http protocol by default.  I apologize for the inconvenience, but you'll have to download Elasticsearch and start it separately.

As such, the options you're looking for are in the https://github.com/logstash-plugins/logstash-output-elasticsearch_java plugin.  They have no part in the default [http protocol] plugin (and I agree that the blog could be more specific regarding which protocol those arguments go with there).

**Comment by rparkhunovsky** [comment]
The same is true for `cluster` option and the inaccuracy in the blog post (still not fixed).
Could you please provide explanation on the `cluster` option absence in this very plugin?

Thanks.

**Comment by untergeek** [comment]
[`cluster`](https://github.com/logstash-plugins/logstash-output-elasticsearch_java/blob/master/lib/logstash/outputs/elasticsearch_java.rb#L135) is only needed in the [`elasticsearch_java`](https://github.com/logstash-plugins/logstash-output-elasticsearch_java) plugin, as you it creates a client node and needs that information to connect to the cluster.  The http-only plugin (this one, which is the new default) does not need the cluster name to connect.  It only requires the IP/host and port number.

**Comment by andrewvc** [comment]
@nlopes I'm going to close this since we won't be bringing embedded back. Unfortunately the embedded version of ES created far more problems than it solved. Thanks for the feedback however!

**Comment by jordansissel** [comment]
@rparkhunovsky you are right about our mistakes in how we removed the cluster and other settings in both how they were removed and also not well documented.
