### ISSUE TITLE
Allow setting the number of replicas for Logstash indexes

### ISSUE THREAD

**Issue by Sodki** [logstash-plugins/logstash-output-elasticsearch#324]
Hi,

I would like to specify the number of replicas for Logstash indexes via Logstash itself. Currently we have to do it via Elasticsearch, but since Logstash is the one creating the indexes I think it makes sense to have this feature as well.

Many thanks.

**Comment by untergeek** [comment]
Hi @Sodki.  This is handled by the [Elasticsearch index template](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html) (and [logstash-output-elasticsearch plugin comes with one](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/elasticsearch-template.json)), rather than a setting inside Logstash.  In fact, strictly speaking, Logstash never sends a "create index" request to Elasticsearch.  It sends "index this document into this named index" requests instead, and Elasticsearch creates the index if it is not yet in existence.  This is why using index templates is the appropriate way for Logstash to handle shard counts.

For reference, Logstash's template management settings are documented [here](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-template).

**Comment by Sodki** [comment]
Right, so this explains why `action.auto_create_index` can never be set to false. I'm already using index templates, but it was very nice of you to take the time and explain it. I'm closing this issue because now I understand it makes no sense with the current design choices.
