### ISSUE TITLE
please undo the mapping change

### ISSUE THREAD

**Issue by gabrielcrowdtilt** [logstash-plugins/logstash-output-elasticsearch#341]
This commit may appear to be an improvement, but what actually happens is .. for an existing logstash parsing which was working, now it arbitrarily breaks on fields where the mapping sets another datatype rather than string. This means certain loglines disappear into the error log and generate spew. On any given day, different fields will error. The application needs to be able to work correctly with the defaults and this change makes it not possible. 

https://github.com/logstash-plugins/logstash-output-elasticsearch/commit/ed8ea6722c8653314a402f585924c78ec7640de3

**Comment by untergeek** [comment]
If you have a custom mapping, you should continue to use it.  Logstash ships with a default mapping template for those who don't use one at all, to help make the new user experience better.

Also, the only real changes to the mapping (since previous versions) are `doc_values` everywhere; mapping the geo_ip latitude, longitude, and location; and the cosmetic/non-functional addition of field types to help users make their own mapping.  The mappings for `float, double, byte, short, integer, long`, and `date` `_fields` will never automatically pick up the numeric types.  If you were to manually map a `byte` somewhere else, these mappings may be added to it, but these are sane defaults to help Elasticsearch and should not cause conflict between numeric and string types.

I'm curious to know what your mapping is and why you're experiencing difficulty, and also which versions of Elasticsearch and Logstash you're using.

**Comment by andrewvc** [comment]
Given the lack of activity here I'm closing this. If you would like to discuss this further @gabrielcrowdtilt please open a new issue.
