### ISSUE TITLE
metadata substitution does not work for variables that expect file paths

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-output-elasticsearch#344]
Take the following as an example (reproducible on LS 2.1.1):

```
filter {
ruby {
    init => "@indexer_host = 'test'"
    code => "
        @truststore = '/Users/Test/Downloads/' + @indexer_host + '.jks'
        event['@metadata']['truststore'] = @truststore
        "
}
}

output {
  elasticsearch{
    truststore => "%{[@metadata][truststore]}" # does not work
    #template => "%{[@metadata][truststore]}" # another field that expects file system path also doesn't work
    # index => "%{[@metadata][truststore]}"  # this works
  }
}
```

The index field works because  the ES output fails with the following message (expected):

```
00, "error"=>{"type"=>"invalid_index_name_exception", "reason"=>"Invalid index name [/Users/Test/Downloads/test.jks], must not contain the following characters [\\, /, *, ?, \", <, >, |,  , ,]", "index"=>"/Users/Test/Downloads/test.jks"}}}, :level=>:warn}
```

But if you try to substitute into a parameter that expects a file system path (eg. truststore, template, etc..), then it throws an error at config validation time:

```
Invalid setting for elasticsearch output plugin:

  output {
    elasticsearch {
      # This setting must be a path
      # File does not exist or cannot be opened %{[@metadata][truststore]}
      template => "%{[@metadata][truststore]}"
      ...
    }
  } {:level=>:error}
```

**Comment by ppf2** [comment]
Discussed with @jordansissel earlier today. There's actually nothing special about strings vs paths, but it matters whether or not the value is passed to event.sprintf or not during logstash's run.  The user can't easily tell from the config declaration because sprintf support comes from a choice in each plugin's executing code.  For the 2 settings tested for example, they are not great candidates for sprintf/formatting. Templates are setup at logstash startup time and at that time no event has occurred. Trust store is for the connection, not per event, and we assume that the output will probably only really have one kind of connection to Elasticsearch, not per event.  We will treat this as a feature request.  For now, we will work on better documenting which settings can actually work with metadata substitution.  

A recommended workaround is to use sed, m4, to generate the LS config from a template prior to starting LS.  See example [here](https://github.com/elastic/logstash/issues/1910#issuecomment-59634201) courtesy of @jordansissel :)

**Comment by erik-stephens** [comment]
Wanted to chime in with my use case.  I was following along with the [nmap+logstash blog post](https://www.elastic.co/blog/using-nmap-logstash-to-gain-insight-into-your-network).  I want to parameterize the template so that the nmap config will play nice with my existing configs.  As much as possible, I try to keep one source's config independent from others.  I use the [@metadata] namespace to coordinate/configure shared snippets such as the elasticsearch output.

Can anyone suggest a workaround?  Having multiple elasticsearch output blocks and wrapping those in `if` blocks is the best I can come up with.  Thanks!

**Comment by andrewvc** [comment]
@erik-stephens multiple if blocks is definitely the best solution to this at the moment.

**Comment by hvisage** [comment]
@andrewvc I have a case where I need to update the templates for each new version of log writer that comes in, it would've been extremely simple to have this:

``` 
   elasticsearch {
        host => localhost
        port => 9300
        index => "index-%{ploneversion}-%{logversion}-%{+YYYY.MM.dd}"
        template => "/etc/logstash/templates/elasticsearch-index-%{ploneversion}-%{logversion}-template.json"
        template_name => "toaster-%{ploneversion}-%{logversion}"
     }
```

But now it'll be quite a bunch of `if` statements coming up ;(
@jordansissel any ideas how you would do similar to the above?

**Comment by andrewvc** [comment]
@hvisage the problem here is that we only do template setup on startup. 

I think you'll realistically want a custom plugin to do this. If you'd like to patch the current plugin I think we'd consider it, but it'd be good if you could reply with a plan for exactly how that would work.

**Comment by hvisage** [comment]
Yes, I can see the template setup is only done at startup, but that then quite limits me. 

Perhaps the solution would be to have a preamble/initial load values for the plugin, to get a list of files from an array and/or grok/file-expansion list and/or directory, and to load all of them into Elasticsearch, and then to assign each template name as need be when indexes are generated for that day/hour/minute for the relevant index-%{LogVersion}-%{TimeStamp} based on the Template-%{LogVersion} variable or template name. %{LogVersion} to be a complex set of variables for extension purposes.

This way I could add extra templates as a new %{LogVersion} log types are defined (with various analyzers like WhiteSpace for some fields that needs to stay CamelCase etc. while the next one could be using another analyzer for some other fields), and then doing a restart, these would get added/inserted into Elasticsearch, and as the new data starts trickling in it'll get used, and as the old versions are still lingering around (because of the rural nature of the device deployments), we would still have the relevant templates available once those historical log-type entries comes in.

Hope I explained myself well, but it's again a "must have this working now, not time/nor-money for decent solution" case and I'll have to do the brute force mechanism for now ;( 
so no, I've not thought this out well yet, but see the need/etc. to modify the plugin/custom-plugin accordingly.

**Comment by mostolog** [comment]
Hi.

I have reached this trying to define elasticsearch templates from logstash: https://discuss.elastic.co/t/templates-mappings-defined-by-logstash/64739

Is there any plan to implement this feature? Is there any workaround?
Thanks

**Comment by jsvd** [comment]
IMO the template options in the ES option are mostly well suited for getting started experiences and for reasons explained above having logstash dynamically create templates at data ingestion time can be harmful to performance.

What is left is to consider an option to load not one but multiple templates, but that is outside the scope of this issue.

I am going to close this for now due to lack of activity, please reopen an issue if you have a use case that requires installing multiple templates in a single es output.
