### ISSUE TITLE
uninitialized constant LogStash::Outputs::ElasticSearch::HttpClientBuilder::Logstash

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-output-elasticsearch#378]
From https://github.com/elastic/logstash/issues/4741

--------------------------------------------------------------------------------------

```
input {
    file {
        path => "/path/to/any/where/trace.log"
        start_position => beginning
        type => "test"
    }
}


output{
  elasticsearch{
    action => "update"
    document_id => "3"
    index => "test"
    document_type => "test"
    script => "ctx._source.obj.status='Wener'"
    upsert => '{"obj":{}}'
    scripted_upsert => true
    doc_as_upsert => true
  }
  stdout{
    codec => rubydebug{
      metadata => true
    }
  }
}
```

if I remove `doc_as_upsert => true` the error will dismiss.Maybe the error report should be more clear ?

logstash 2.2.2

**Comment by suyograo** [comment]
@Da-Wei any ideas?

**Comment by jayswan** [comment]
Does this bug mean that `doc_as_upsert` and `scripted_upsert` are mutually exclusive in the current version?

I have a config like this:

```
output {
    elasticsearch {
        action => "update"
        doc_as_upsert => true
        document_id => "%{ip}"
        script_type => "file"
        scripted_upsert => true
        index => "total"
        script => "total_upsert"
    }
}
```

which fails with this error. My goal is this:

- If the document id exists, update it
- If the document id doesn't exist, index it but add a field using the script.

Those two things work independently but when I try do combine them by having both `doc_as_upsert` and `scripted_upsert` set to true, it produces the error.

**Comment by omercnet** [comment]
having same issue

**Comment by dchauviere** [comment]
@jayswan @omercnet @suyograo , Yes, "doc_as_upsert" and "scripted_upsert" are mutually exclusive ! Logstash should raise an error for that but I made a mistake in the exception name "Logstash::ConfigurationError" instead of "LogStash::ConfigurationError"

@jayswan, you use scripted_upsert, your script need to manage the upsert case (ctx._source is empty. sorry, I haven't any example for checking that ) and you have all the logstash event in the "event" variable !
