### ISSUE TITLE
Disable _all field and use message field as default search field

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-output-elasticsearch#451]
Currently, LS's default index template creates the _all field, which is expensive:  it essentially duplicates data - Lucene will end up having to index the data 3 times, into fields, to _all and then message.  This means increased indexing and merge times, additional heap usage for terms index and terms dictionary, additional disk space, etc..  It's expensive and wasteful per the Lucene devs

The alternative will be to disable _all entirely for the LS index template and set index.query.default_field to message field by default. If there are supported plugins that are not generating the message field, we will want to look into why that is.  

This is to start a discussion on this topic to see if there is an opportunity for optimization here.

@rmuir @suyograo @jordansissel

**Comment by suyograo** [comment]
I am generally +1 on this. Particularly for logging use case it makes more sense given the volume of data that gets ingested -- we should do our best to reduce disk space. IMO, logging users will want to search on `message` or do a field qualified search rather than search against the `_all` field. If a user wants `_all` field, they can always choose to have this indexed.

To support the savings in disk space or increasing indexing throughput can we substantiate this change with numbers on both ends? This will make it easy..

> If there are supported plugins that are not generating the message field, we will want to look into why that is 

I don't know what those plugins are. Maybe @jordansissel can chime in here?

**Comment by rmuir** [comment]
I guess to me the waste seems to be to have customers with `message` and `_all`.

I do think, `message` can only ever be so good, because it will have a bunch of numbers (e.g. timestamps) and other junk in it, as strings, thats gonna blow up disk space and stuff. Its not gonna really search very well either honestly, being indexed in that way. I know `_all` does that too, but thats something we could potentially fix on the ES side, so that it only brings in strings or whatever.

For log data, indexing timestamps as strings (either as a field, or  inside `message` or `_all`) is very expensive. Its about as costly as an ID field.

Its not just the space, but the terms/postings are the bottleneck for merging costs/indexing performance as well.

**Comment by jsvd** [comment]
_all is deprecated in ES 6.0 and will be removed in 7.0
Unless there's some urgency in addressing this we can close this issue and wait for the obsoletion.
