### ISSUE TITLE
Ingest Pipeline parameter should support variables/dynamic

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [logstash-plugins/logstash-output-elasticsearch#491]
It seems that the only acceptable value of the [pipeline](https://www.elastic.co/guide/en/logstash/5.x/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-pipeline) parameter is a static string.  It would be helpful if we could use `%{variables}` .

In a particular use case, we have a pipeline designed to process each document type, but Logstash must route on `_type`.

An important consideration would be - what if the pipeline doesn't exist?  Perhaps Elasticsearch could have an option to route to a default pipeline in that case.

**Comment by dkolli** [comment]
Thanks Jay for submitting this enhancement request.

**Comment by PhaedrusTheGreek** [comment]
Thinking about this some more, and as @clintongormley pointed out, we can do pipeline existence just as well in Logstash with `if/elseif/elseif/else/`.

**Comment by dkolli** [comment]
I thought of that as well. The issue with that approach is that, everytime a new type of the logs comes   in you need to add another elseif. Just more maintenance and it does't automate routing to the  pipeline.

**Comment by dkolli** [comment]
What I would like to see is that, logstash is more like a pipeline router (not a parser), so i don't have to touch the configuration whenever a  new log type comes in. I'd push the parsing to ingest node pipelines (one pipeline per type of the log, so that pipeline will be small with less rules and more efficient), if the pipeline does not exist, ingest node/elasticsearch should be able to route that message to a default pipeline, so that way I wouldn't lose a message (although it is not parsed). We can monitor those and build/create new pipelines through Rest API, so new logs would automatically be processed. this way, we can avoid new deployments of log stash configs etc.

**Comment by suyograo** [comment]
Fixed in #508 

Please open a separate issue for pipeline routing.
