### ISSUE TITLE
template not posted if elasticsearch is not running upon startup

### ISSUE THREAD

**Issue by jpcarey** [logstash-plugins/logstash-output-elasticsearch#521]
- Version: 5.0.2, 2.3.1
- Steps to Reproduce:
1. Start logstash with elasticsearch output configured, but elasticsearch not running. Create some messages to be flushed to elasticsearch (stdin...)

5.0.2: `[2016-12-06T07:13:15,077][ERROR][logstash.outputs.elasticsearch] Failed to install template. {:message=>"Elasticsearch Unreachable: [http://~hidden~:~hidden~@localhost:9200][Manticore::SocketException] Connection refused", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError"}`

2.3.1: `Connection refused {:class=>"Manticore::SocketException", :level=>:error, :file=>"logstash/outputs/elasticsearch/template_manager.rb", :line=>"11", :method=>"install_template"}`

2. Start elasticsearch. The logstash template will not exist, but the logstash-YYYY.MM.dd index will be created. Without the template, the index will use automatic mappings (so every string is analyzed) producing a very undesired and unexpected result.

It seems that during `register`, `build_client` will setup `@client = ::LogStash::Outputs::ElasticSearch::HttpClientBuilder.build()` with no living connection, and the `install_template` uses this and quickly fails with no further retries.  It seems like it should retry the template once the connection is live, but this looks rather tricky since the event loop will start and just try "Flushing buffer at interval" until it is successful.

**Comment by jpcarey** [comment]
@untergeek I agree. My thinking was along the lines of on first startup, if the template fails - we note /store that - and put that as a task item to be "tried" (could still fail due to mapping, etc) before flushing the first queue / buffer of events?

**Comment by untergeek** [comment]
I don't see such a fix as a worthwhile pursuit.  It's a tremendous amount of recoding and system checking for something that only happens under extremely rare circumstances.  And that's being fairly generous, I think.  Once users have a template in place, they seldom need to alter it—it just sits there and new indices get made with the defined template/mapping.  And it's so trivial to add the template with a cURL call on the command line that it also seems like a heap of overkill to add so much just for this.

In the future, when Logstash has online configuration and such, this will be addressed very differently, and visually, so that users will deploy a template before Logstash is even started, and be able to see what it looks like, no doubt.

**Comment by jordansissel** [comment]
We could block startup until Elasticsearch output has successfully published the template, although, I fear doing that will just punt the problem -- users will complain that Logstash isn't starting up because Elasticsearch is down.  

I want to feel like we can minimize user experience problems, so I don't to trade one problem for another. 

How do y'all feel about having Logstash block on startup waiting for Elasticsearch to come online?

I agree with @untergeek about how the game might change when we make it possible to store Logstash's configuration in Elasticsearch.

**Comment by untergeek** [comment]
I'm -1 to having Logstash block on startup.  As previously stated, this is not a common problem at all.  I think it would be a lot of work for very minimal return on investment.  I think there are a lot of other areas we could redirect the effort with a better ROI.

**Comment by andrewvc** [comment]
I believe this is currently fixed in master. We currently block all operations until a connection is alive.

**Comment by jsvd** [comment]
this has been solved in https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/758
