### ISSUE TITLE
Logstash ignores the combination of idle_flush_time and flush_size

### ISSUE THREAD

**Issue by orweinberger** [logstash-plugins/logstash-output-elasticsearch#539]
Running Logstash v2.4, I have the following configuration:

```
input {
        generator {
                message => '{"hello": "world"}'
                codec => "json"
        }
}
filter {
        metrics {
                meter => ["events"]
                add_tag => "metric"
        }
}

output {
        if "metric" in [tags] {
                stdout {
                        codec => line {
                                format => "rate: %{[events][rate_1m]} count: %{[events][count]}"
                        }
                }
        }
        else {
                elasticsearch {
                        hosts => ["elastic"]
                        idle_flush_time => 600
                        flush_size => 99999999
                }
        }
}
```

I'm trying to test out both the `idle_flush_time` and `flush_size` params by setting them to very high values, I'm pushing about 1500 events per second and what I'm seeing is that these events are being pushed into Elasticsearch regardless of what I'm defining in these two params. Even though I've asked the output plugin to flush every 600 seconds or every 99999999 events, even on the first batch of generated events I can see them on Elasticsearch, being pushed immediately.

Any ideas?

**Comment by orweinberger** [comment]
To make things a bit clearer, I've added the `count` param to the generator input and set it to `10000`, while the flush size is well above that number and the idle_flush_time is set to 5 minutes, I can see events being inserted immediately to Elasticsearch even though it never reaches the flush_size value.

**Comment by andrewvc** [comment]
@orweinberger thanks for reporting this. 

The `idle_flush_time` should be removed since it does nothing. Events are now sent as quickly as possible since Logstash moved to a batch oriented pipeline. We now send the whole batch all at once.

The `flush_size` parameter is planned to be removed in 6.0. Given this issue here I'm considering removing it earlier than that. `flush_size` only *reduces* the maximum number of events sent at any given time. The only way to increase the number of events sent is with Logstash's `-b` flag for batch size, which defaults to 125.

**Comment by andrewvc** [comment]
The other option would be setting the `flush_size` to default to unbounded then marking it as deprecated. This would be less confusing to most people IMHO.

**Comment by jsvd** [comment]
flush_size has been removed in 8.0.0
