### ISSUE TITLE
Set Content-Type and Accept headers.

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-output-elasticsearch#552]
This is necessary to support https://github.com/elastic/elasticsearch/pull/22691 when it lands. Without fixing this, this input will (likely?) not work against new Elasticsearch releases.

**Comment by jordansissel** [comment]
I tested with Logstash 5.1.1 (ES output v5.4.0) and this is the request sent for /_bulk:

```
POST /_bulk HTTP/1.1.
Connection: Keep-Alive.
Content-Length: 223.
Content-Type: text/plain; charset=ISO-8859-1.
Host: localhost:9200.
User-Agent: Manticore 0.6.0.
Accept-Encoding: gzip,deflate.
```

Content-Type is wrong.

**Comment by andrewvc** [comment]
This was already fixed in #553

**Comment by chekkan** [comment]
Content-Type should be `text/plain` for `_bulk` endpoint `post` as the request body send is json lines and not valid json.

Otherwise, for example, if you are using a proxy for elasticsearch and proxy has a middleware which parses json contents automatically, it will throw an error saying not a valid json.

Another example, the proxy being AWS API Management.

**Comment by andrewvc** [comment]
@chekkan can you open a new issue for this? 

It looks like what elasticsearch wants is [`application/x-ndjson`](https://www.elastic.co/guide/en/elasticsearch/reference/5.x/docs-bulk.html).

**Comment by andrewvc** [comment]
That being said, having a proxy intercepting and decoding arbitrary JSON endpoints to Elasticsearch is probably a bad idea for performance. Can you tell us why you need that? It'd be good to know for future reference.

**Comment by jordansissel** [comment]
@chekkan text/plain is not a choice Logstash (the software) gets to make in this scenario. The Content-Type enforcement comes from Elasticsearch. A new content-type for _bulk was suggested in https://github.com/elastic/elasticsearch/issues/22943  and merged into 5.3 and 6.0 branches as https://github.com/elastic/elasticsearch/pull/22947.

Regarding your middleware concern, it looks like only content types of application/json and application/x-ndjson will be accepted in ES 6.0 for _bulk, so I recommend you test with that, and, if it doesn't work for your scenario, file an issue against Elasticsearch.

**Comment by chekkan** [comment]
Opened issue #561

@andrewvc Currently, we are writing a nodejs api service to act as a proxy to elasticsearch which only intercepts the bulk requests from logstash. This is so that we can handle more complex data transformations to the content and also to gzip compress the data before forwarding it to elasticsearch.

@jordansissel Sorry for any confusion, I was refering to the decision logstash makes when making the post request to `_bulk` http endpoint, which at present is sending `application\json`.
https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/http_client.rb#L131-L135
```
def bulk_send(bulk_body)
      # Discard the URL
      url, response = @pool.post("_bulk", nil, bulk_body)
      LogStash::Json.load(response.body)
end
```

**Comment by jordansissel** [comment]
@chekkan yeah indeed. What I Mean is that in Elasticsearch 6.0, the only accepted content-types for _bulk will be application/json and application/x-ndjson -- text/plain will be rejected.

> This is so that we can handle more complex data transformations to the content and also to gzip compress the data before forwarding it to elasticsearch

Is this proxy to be used with Logstash? My first question is a "why" -- Why do you need this proxy? What behavior of the Elasticsearch output cannot be changed to suit your needs?

**Comment by chekkan** [comment]
@jordansissel Currently, we are writing a nodejs api service to act as a proxy to elasticsearch which only intercepts the bulk requests from logstash. This is so that we can handle more complex data transformations to the content and also to gzip compress the data before forwarding it to elasticsearch.

On top of that, I think the intended purpose for the `path` configuration options for elasticsearch output is so that we can address these scenerios
https://www.elastic.co/guide/en/logstash/master/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-path

For example, consider these two examples
<pre>
# /uk_films.conf
elasticsearch {
    hosts => ['http://localhost:3000']
    index => "films"
    document_type => "film"
    path => "/v1/<b>uk</b>/films"
}
</pre>
<pre>
# /japan_films.conf
elasticsearch {
    hosts => ['http://localhost:3000']
    index => "films"
    document_type => "film"
    path => "/v1/<b>japan</b>/films"
}
</pre>
This allows us to transform both uk and japan data into the same mapping with api versioning

**Comment by jordansissel** [comment]
> also to gzip compress the data before forwarding it to elasticsearch.

For compression, we are adding this to the elasticsearch output (#454, #559).

**Comment by jordansissel** [comment]
> This allows us to transform both uk and japan data into the same mapping with api versioning

Not pressuring, but I want to ask: Would it be easier to use a custom filter for this? Or more generally, what makes you want to write a custom proxy to do this instead of having Logstash do these transforms?

**Comment by dinnot** [comment]
@jordansissel Hi. Imo I think adding support for javascript functions (there are ways to run js in jvm) as plugins would increase usage amongst non-ruby devs. At least for filter plugins which would be easy to implement if in/out plugins would be too complicated.

**Comment by chekkan** [comment]
@jordansissel I am afraid the simplest answer is because I found it really hard to transform the object using the filters available. 

Simple field renames seems to be fine. But, we have a use case where we want to take multiple fields and transform it on to an array. I got somewhere with `mutate -> add_field` but what I found is that if any of the fields are `null` the array had the value `%{field_name1}`. 

I can see other cases where one would need data from another service before indexing it into elasticsearch.

As @dinnot mentioned, we could maybe resolve this using the `ruby` code filter. However, as there are not that many resources with ruby experience in our team, we are finding that option difficult too.
