### ISSUE TITLE
Logstash jdbc type conflicts with statement field

### ISSUE THREAD

**Issue by copywrite** [logstash-plugins/logstash-output-elasticsearch#573]
i have a conf as follows

```
input {
        jdbc {
            statement => 'select type from item'
            type => "item"
        }
}

output {
       elasticsearch {
              document_type => '%{type}'
       }
}
```

the output type value is from statement field.

what i want is the value defined by type => "item".

any sugguestions?

**Comment by untergeek** [comment]
Having `type => "item"` in the input declaration will set the value of field `type` to `item`, regardless of what is in your `statement`.  This is because Logstash "decorates" the event with whatever `tags` you define, as well as `type`, _after_ the input plugin has completed its data collection.  

As data leaves an input block it becomes an event, and the decorator fields `tags` and `type` are added to the event.     

Unfortunately, that makes `type` a semi-protected field. If omit or comment the line `type => "item"`, it should work, as there will be no decorator added for `type` in this case.  The other possibility is to change your SQL to `select type from item as mytype`, and use the field `mytype` instead.

In the future, please ask usage questions at https://discuss.elastic.co/c/logstash as GitHub issues are reserved for requesting code changes and broken functionality.  In the event that we are unable to help you in the discussion forums, we escalate from there to here.

**Comment by untergeek** [comment]
I should also mention that 
```
document_type => '%{type}'
```
is implicit in the Elasticsearch output plugin.  If a `type` field exists, that value will always be used as the `document_type`.  Because Elasticsearch requires a "type" for mapping, if _no_ `type` field exists in a Logstash event, a default of `logs` will be assigned.

**Comment by copywrite** [comment]
@untergeek 
Clearly learnt.

`select type from item as mytype` is a good choice.
