### ISSUE TITLE
bring back ignore_above in the default template for keyword fields?

### ISSUE THREAD

**Issue by jakommo** [logstash-plugins/logstash-output-elasticsearch#588]
The default [template for 2.x used ignore_above for the .raw](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/f4cf5b67b6776d847df32f38d4fd95f835e109e0/lib/logstash/outputs/elasticsearch/elasticsearch-template-es2x.json#L26) fields. 
In the 5.x template, [this is not being used anymore](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/f4cf5b67b6776d847df32f38d4fd95f835e109e0/lib/logstash/outputs/elasticsearch/elasticsearch-template-es5x.json#L26). 
This could lead to rejections when the content of a `.keyword` field exceeds Lucene’s term byte-length limit of 32766.

I'm not sure if we should bring it back, as it would silently accept the field without it being indexed or stored and the rejection might raise awareness to the user that he probably does not want a long text as a keyword field, but there might be use cases where the old behavior was intended.
Just want to start a discussion, if we should introduce [ignore_above](https://www.elastic.co/guide/en/elasticsearch/reference/current/ignore-above.html) again or keep it like it is.

**Comment by andrewvc** [comment]
@suyograo @untergeek do either of you know if this removal was a conscious choice? If so, why?

**Comment by untergeek** [comment]
I'm not 100% sure, but I think ES 5 handles that he default. It _seems_ to, anyway.

**Comment by jsvd** [comment]
Since we overwrite the default keyword mapping which in elasticsearch contains the `"ignore_above": 256`, we should include this again.
An alternative would be to remove [the whole block of `string_fields`](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/f4cf5b67b6776d847df32f38d4fd95f835e109e0/lib/logstash/outputs/elasticsearch/elasticsearch-template-es5x.json#L20-L29), but this template is disabling norms for text fields, which ES doesn't do by default.

**Comment by jsvd** [comment]
tentatively tagging this as a bug
