### ISSUE TITLE
Make 403 response configurable for going into DLQ

### ISSUE THREAD

**Issue by jpcarey** [logstash-plugins/logstash-output-elasticsearch#697]
When a 403 response is encountered, this is retried forever. This blocks the pipeline from continuing to process (https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/140). This is good in the event of a major misconfiguration since the entire pipeline becomes blocked. This can be bad in the case where just a couple messages are routed to indices that might be closed out due to automatic curation. The behavior of a 403 messages should be configurable, so it could go into the DLQ.

```
[2017-10-24T15:31:30,232][INFO ][logstash.outputs.elasticsearch] retrying failed action with response code: 403 ({"type"=>"index_closed_exception", "reason"=>"closed", "index_uuid"=>"Lnvl85mrRtSOGDzZnb86gw", "index"=>"test_dlq"})
```

Discussed with @jordansissel, and agree this should not be the default behavior - since putting in the DLQ only extends the amount of time before the pipeline is stalled (due to a full DLQ). However, it should be a choice an end user can configure for desired behavior.

**Comment by tomsommer** [comment]
What about just discarding the 403? I don't want anything to stall in case something is sent to a few closed indexes.

**Comment by jsvd** [comment]
I'm ok with having this configurable and off by default (current behaviour)

**Comment by chandlermelton** [comment]
I have noticed that my Logstash pipelines have become less resilient to this problem since my upgrade from 5.1.2 to 5.6.9. I am looking into implementing DLQ for this. (My issue is that a server will come out of a day or weeks old maintenance and filebeat will attempt to ship any unsent logs near the time of the original crash into an index which has since been closed.)

Perhaps an option could also be adding a tag or flag on an index which could instruct Logstash's response. ( index_when_closed_repsonse: "DLQ / drop / new_target_index" )
