### ISSUE TITLE
elasticsearch document and logstash-output-elasticsearch implementation have contradiction

### ISSUE THREAD

**Issue by snuffkin** [logstash-plugins/logstash-output-elasticsearch#738]
Elasticsearch Reference says "The preferred type name is _doc".
https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html#_schedule_for_removal_of_mapping_types2

But, logstash-output-elasticsearch sets "doc" to the type field for default.
https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/common.rb#L207

Should logstash-output-elasticsearch set "_doc" to the type field?

**Comment by webmat** [comment]
Hello, yes we know this is a discrepancy with the ES documentation. The issue is that support for "_doc" in ES only appeared in 6.2.0, not 6.0.0.

Currently our support matrix for how to interact with ES in the output plugin is on major versions (e.g. 6 vs 7), not major.minor. So we can't automatically go to "_doc" on ES 6, because of pre-6.2 versions.

So by default the output plugin uses "doc" on 6 and will automatically use "_doc" when talking to ES 7. Note also that ES 7 will still support "doc", so rolling upgrades will not be a problem. So if you use the plugin without touching the type, everything will work.

If you really want to move to "_doc" right away, you can do so via the (deprecated) `document_type` plugin attribute.

If you have a strong opinion on adding support for "_doc" on 6.2+ in the output plugin, please join the conversation over in issue #734.
