### ISSUE TITLE
[ 1.5.0rc2 ] : Allowing log verbosity configuration in the "elasticsearch" output

### ISSUE THREAD

**Issue by chiriaev** [logstash-plugins/logstash-output-elasticsearch#75]
Guys, Hi. I am testing the latest "1.5.0 rc2". I have a couple of Rabbit inputs with four threads each. The output uses the latest "elasticsearch" plugin. There is one very annoying difference between the latter and the deprecated "elasticsearch_http" plugin. Any "POST /_bulk" response with one or more records with a "status" of, for example, 400 or 429, etc..., will generate "warn" level log data corresponding to the original bulk request. In my case I can have dozens of megabytes per seconds. A configuration option controlling this behaviour would be mostly welcome. (i.e.: the Rabbit input has it by the way)

Thanks in advance.

Regards, Andrei

P.S.: transferred from elastic/logstash#2847

**Comment by untergeek** [comment]
This will generate a lot of warning messages for potentially no good reason.  Since the elasticsearch output plugin now does automatic retries in the event of a send fail, I can see no good reason to get a warning every time this happens.  Our current goals for Logstash 2.0 also involve a dead-letter queue, with separate notifications if things refuse to resend after _n_ tries.

I'm not sure we need this feature in light of these things.

**Comment by chiriaev** [comment]
Thanks, Aaron. Do you mean that the "warning" should be dropped? When is the "2.0" expected? Shouldn't we perhaps have that feature implemented in the meantime? I can't use the "1.5" plug-in generation unless the log level could be set to "error", for example. 

Regards, Andrei

**Comment by untergeek** [comment]
Yes. I am implying that there should be no warning for retries because the current version of the plugin automatically retries on 429 and 503 messages. 

Logstash 2.0 is a separate matter from retries and logging.

**Comment by untergeek** [comment]
Closing this.  We've rehashed this with regards to retries several times over.
