### ISSUE TITLE
Elasticsearch output plugin index option has invalid example

### ISSUE THREAD

**Issue by wmassingham** [logstash-plugins/logstash-output-elasticsearch#876]
https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-index

The default option listed says "Default value is `"logstash-%{+YYYY.MM.dd}"`. However, that is invalid, the year should be lower case: `"logstash-%{+yyyy.MM.dd}"`.

https://discuss.elastic.co/t/logstash-not-creating-index-daily-based-on-date/189306

**Comment by j-ledoux** [comment]
Indeed it helped me fixed logstash daily index creation that was stuck on the first day it started.

**Comment by jgrevich** [comment]
This seems more like a bug since I don't understand why `YYYY` year of era would not work, albeit with the potential of having an incorrect year (https://www.juandebravo.com/2015/04/10/java-yyyy-date-format/). I'm not suggesting that `yyyy` isn't the better value here just that both should work as it has in previous versions. On my cluster using `index => "logstash-%{+yyyy.MM.dd}"` results in an index named `logstash`. Oddly, I have similar pipelines for cloudtrail and cloudwatch which also use the ES output plugin. However, the same index pattern using `YYYY` seems to work fine with those pipelines. Odd.

**Comment by karenzone** [comment]
Note to self (@karenzone): Research to determine if this is a doc fix and/or a bug.  See https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/876#issuecomment-538619053

**Comment by jgrevich** [comment]
> Oddly, I have similar pipelines for cloudtrail and cloudwatch which also use the ES output plugin. However, the same index pattern using `YYYY` seems to work fine with those pipelines. 

I was wrong, the other pipelines were using the `yyyy` style and did not exhibit this issue.

**Comment by szogun1987** [comment]
Changing format to lowercase helped me. Maybe it is OS related issue. I run whole ELK stack on Windows machines.

**Comment by eavilesmejia** [comment]
I was faced the same issue on RHEL 7 and switched to lowercase fixed the issue

**Comment by karenzone** [comment]
Thank you all for opening/commenting in this issue.  <3
Should be resolved now.

**Comment by Superernest8** [comment]
This is an OS related issue !!
