### ISSUE TITLE
[Doc]Remove old compatibility notes

### ISSUE THREAD

**Issue by karenzone** [logstash-plugins/logstash-output-elasticsearch#936]
These notes don't make sense in 7.x (or 6.x for that matter). Documentation for older versions is still available if somebody needs it.

<img width="733" alt="Screen Shot 2020-04-17 at 11 16 14 AM" src="https://user-images.githubusercontent.com/35154725/79584826-ec8ae300-809c-11ea-98c9-0962b85419d5.png">

<img width="836" alt="Screen Shot 2020-04-17 at 11 16 22 AM" src="https://user-images.githubusercontent.com/35154725/79584851-f44a8780-809c-11ea-95cf-079f6ee09ca6.png">

**Comment by yaauie** [comment]
+ 1 to removing these from modern docs, since Logstash 2.x was EOL'd on 2018-02-28 with the release of 6.0.

These docs will continue to exist in the versioned-docs archive, so users who are still in this situation will be able to find them (e.g., we recommend updating through each major's last minor when doing multi-major upgrades, so someone who missed the boat for 5.x in 2016 and is just now planning a 2.x->7.x upgrade will still need this info).
