### ISSUE TITLE
Healthcheck fails in weird ways when response is an HTTP 404

### ISSUE THREAD

**Issue by yaauie** [logstash-plugins/logstash-output-elasticsearch#954]
`ManticoreAdapter#perform_request` explicitly counts an HTTP 404 as a non-exceptional condition, which allows the healthcheck to get into a weird state when reviving a connection (which can occur during initialization), specifically when we send `Pool#get_es_version(url)` and expect the response to be a specific shape.

We need to validate that we received a 2XX level response code from the initial healthcheck ping, ideally one that validates the shape of the repsponse to be Elasticsearch-y, and we need to make the whole code more resilient to non-success paths in `Pool#get_es_version(url)`.

**Comment by TheVastyDeep** [comment]
The get_es_version function in the pool.rb certainly makes assumptions about the shape of the response (i.e. that it is valid JSON and the version field contains a number sub-field. If those assumptions are violated the result is an exception that prevents the pipeline starting but which gives absolutely no indication of what the problem is until you enable DEBUG logging.
